In [4]:
import numpy as np


In [30]:
a=np.arange(10)
b=np.array([[1,2,3] , [1,2,3]])
print(a,b)
print(b.ndim)
print(b.dtype)
print(b.size)
print(b.itemsize)

[0 1 2 3 4 5 6 7 8 9] [[1 2 3]
 [1 2 3]]
2
int32
6
4


In [36]:
c=np.array([(1,2,3) , (1,2,3),(4,5,6),(1,2,3)])
print(c.ndim)
print(c.dtype)
print(c.size)
print(c.itemsize)
print(c)

2
int32
12
4
[[1 2 3]
 [1 2 3]
 [4 5 6]
 [1 2 3]]


In [38]:
print(c.shape)
c.reshape(3,2,2)

(4, 3)


array([[[1, 2],
        [3, 1]],

       [[2, 3],
        [4, 5]],

       [[6, 1],
        [2, 3]]])

In [39]:
print(c)

[[1 2 3]
 [1 2 3]
 [4 5 6]
 [1 2 3]]


In [45]:
c[:2,2]

array([3, 3])

In [48]:
d=np.linspace(1,3,10)
print(d)

[1.         1.22222222 1.44444444 1.66666667 1.88888889 2.11111111
 2.33333333 2.55555556 2.77777778 3.        ]


In [54]:
c.sum()
c.min()
c.max()

6

In [56]:
c.sum(axis=0)
c.min(axis=0)

array([1, 2, 3])

In [67]:
a=c
print(a)
a=np.sqrt(a)
print(a)
print('---------')
print(np.vstack((a,c)))
print('---------')
print(np.hstack((a,c)))

[[1 2 3]
 [1 2 3]
 [4 5 6]
 [1 2 3]]
[[1.         1.41421356 1.73205081]
 [1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [1.         1.41421356 1.73205081]]
---------
[[1.         1.41421356 1.73205081]
 [1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [1.         1.41421356 1.73205081]
 [1.         2.         3.        ]
 [1.         2.         3.        ]
 [4.         5.         6.        ]
 [1.         2.         3.        ]]
---------
[[1.         1.41421356 1.73205081 1.         2.         3.        ]
 [1.         1.41421356 1.73205081 1.         2.         3.        ]
 [2.         2.23606798 2.44948974 4.         5.         6.        ]
 [1.         1.41421356 1.73205081 1.         2.         3.        ]]
